### ISSUE TITLE
Request PID Values nappi antaa tämmöstä

### ISSUE THREAD

**Issue by firkka** [Waakken/serial_gui#4]
Traceback (most recent call last):
  File "/home/jukka/Desktop/serial_gui-master/arduinogui/ArduinoguiWindow.py", line 194, in on_request_pid_button_clicked
    floats = self.unpackBinary(response)
  File "/home/jukka/Desktop/serial_gui-master/arduinogui/ArduinoguiWindow.py", line 34, in unpackBinary
    floats = struct.unpack("18f", data)
struct.error: unpack requires a string argument of length 72

**Comment by firkka** [comment]
Lisättäköön, että pyyntö tulee kopterin mbedille ja kopteri saa ACK:n vastaanotetusta paketista, eli varmaan GUI:n pakettikoossa jotain hämminkiä.

**Comment by Waakken** [comment]
Mikä on paketti koko minkä Mbed on lähettäny GUI:lle tos tapaukses? Näkyy "Size of last messagen" oikeel puolella? Voin lisätä toho unpack:in mukautuvan koon, mut ei pitäis olla tarpeen
